### ISSUE TITLE
SwaggerCodeGen not working any more?

### ISSUE THREAD

**Issue by tsproesser** [swagger-api/swagger-codegen#10140]
Right now the latest hosten version http://editor.swagger.io/ can't generate code for any platform. Not even with the initial example data used. I've tried to host an older Docker image but still the same error. Sorry for the short description, but pretty busy right now.

What's wrong here?

**Comment by hkosova** [comment]
Online codegen should work now. Can you please try again?

**Comment by tsproesser** [comment]
Still not working: Error generating `typescript-angular` code : Could not generate model '[generic]'.

**Comment by tsproesser** [comment]
> Online codegen should work now. Can you please try again?

I'm having a problem with http://generator3.swagger.io/ - fyi

**Comment by hkosova** [comment]
@tsproesser online codegen had another hiccup but it was taken care of. Does it work for you now?

**Comment by tsproesser** [comment]
Yes, it's working again. And any help with the Swagger Container would be appreciated 👍

**Comment by frantuma** [comment]
@tsproesser 

> Btw: can you please tell me how to setup the "swaggerapi/swagger-generator-v3" Docker image? There is no docu (like for the "swaggerapi/swagger-generator") and it just comes up with a 404.

please see [this readme section](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/README.md#online-generators)

**Comment by tsproesser** [comment]
> @tsproesser
> 
> > Btw: can you please tell me how to setup the "swaggerapi/swagger-generator-v3" Docker image? There is no docu (like for the "swaggerapi/swagger-generator") and it just comes up with a 404.
> 
> please see [this readme section](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/README.md#online-generators)

Thank you very much! But the mentioned image just doesn't work? Am I doing anything wrong? The v1 /v2 generator ("waggerapi/swagger-generator") works, editor works and converter works. But that -v3 image just seams broken.

**Comment by frantuma** [comment]
@tsproesser

the docker image is `swaggerapi/swagger-generator-v3` (https://hub.docker.com/r/swaggerapi/swagger-generator-v3/, see [here](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/README.md#public-pre-built-docker-images)

you run in docker via:

```
docker pull swaggerapi/swagger-generator-v3

docker run -e "JAVA_MEM=1024m" -e "HTTP_PORT=80" -p 80:80 --name swagger-generator-v3 -v /tmp:/jetty_home/lib/shared swaggerapi/swagger-generator-v3
```


the UI is available at: http://localhost/index.html

The mandatory link will is planned to be fixed in next release

Please let me know if you have further issues or questions, otherwise please close ticket, and thanks for reporting the problem.
