### ISSUE TITLE
How can I map boolean data type in Swagger Specification to NSNumber in Objective C client SDK.

### ISSUE THREAD

**Issue by sohail-aspose** [swagger-api/swagger-codegen#1097]
I am using swagger-codegen to generate client SDK in Objective C language. One of my APIs is taking boolean parameter. Parameter is defined in Swagger Specification as follows:

    "parameters": [
        {
            "name": "recursive",
            "in": "query",
            "description": "",
            "required": false,
            "type": "boolean"
        }
    ]
The generated client SDK is checking if BOOL variabe is nil. BOOL is a primitive type in Objective C, cannot be checked against nil. It is causing compilation error.
    
    -(NSNumber*) folderDeleteFolderWithCompletionBlock: (NSString*) path recursive: (BOOL) recursive {
        ...
        if(recursive != nil)
        {
            queryParams[@"recursive"] = recursive;
        }
        ...
    }
If we use NSNumber ```+ (NSNumber *)numberWithBool:(BOOL)value``` in place of BOOL, this issue can be fixed. How can I map ```boolean``` in swagger specification to ```NSNumber``` in client SDK?

I made few changes in ```ObjcClientCodegen.java``` like replace following line

    typeMapping.put("boolean", "BOOL");
with
    
    typeMapping.put("boolean", "NSNumber");

Even remove ```BOOL``` from ```defaultIncludes``` and ```languageSpecificPrimitives``` HashSets

    defaultIncludes = new HashSet<String>(
                Arrays.asList(
                        /*"bool",
                        "BOOL",*/
                        "int",
                        "NSString",
                        "NSObject",
                        "NSArray",
                        "NSNumber",
                        "NSDate",
                        "NSDictionary",
                        "NSMutableArray",
                        "NSMutableDictionary")
        );
        languageSpecificPrimitives = new HashSet<String>(
                Arrays.asList(
                        "NSNumber",
                        "NSString",
                        "NSObject",
                        "NSDate"/*,
                        "bool",
                        "BOOL"*/)
        ); 
but still generated client SDK is using BOOL data type instead of NSNumber. 

Any help in this regard will be highly appreciated.

**Comment by wing328** [comment]
@sohail-aspose thanks for reporting the issue. To confirm, are you testing with the latest ObjC SDK from `develop_2.0` branch?

**Comment by sohail-aspose** [comment]
No, I am using ObjC SDK from `master` branch. Should I use SDK from `develop_2.0` branch?

**Comment by geekerzp** [comment]
@sohail-aspose  It is fixed in `develop_2.0`, please have a try.

**Comment by sohail-aspose** [comment]
OK, let me try. Thank you very much for the prompt reply.

**Comment by sohail-aspose** [comment]
Unfortunately problem is still there. ```develop_2.0``` branch has lot of other issues as well.

**Comment by wing328** [comment]
I did a test with petstore by changing `additionalMetadata` to boolean (required) and got the following:
```
-(NSNumber*) uploadFileWithCompletionBlock: (NSNumber*) petId
         additionalMetadata: (NSNumber*) additionalMetadata
         file: (NSURL*) file


        completionHandler: (void (^)(NSError* error))completionBlock {

   
    // verify the required parameter 'petId' is set
    if (petId == nil) {
        [NSException raise:@"Invalid parameter" format:@"Missing the required parameter `petId` when calling `uploadFile`"];
    }
   
    // verify the required parameter 'additionalMetadata' is set
    if (additionalMetadata == nil) {
        [NSException raise:@"Invalid parameter" format:@"Missing the required parameter `additionalMetadata` when calling `uploadFile`"];
    }
```
so `boolean` is represented as `NSNumber` in Objc client.

Did you perform a `mvn clean package` before generating the Objc client in develop_2.0 branch ?

**Comment by sohail-aspose** [comment]
```mvn clean package``` did the trick. Thank you for your kind cooperation.

**Comment by wing328** [comment]
@sohail-aspose no problem. Let us know if you've any feedback or question on the ObjC SDK.

**Comment by sohail-aspose** [comment]
One more question :) My one API returns a file e.g. image, MS Word document, PDF file etc. What return type should I use in Swagger Specification. 

    "responses": {
        "200": {
            "description": "OK",
            "schema": {
                "type": "???"
            }
        }
    } 
In ObjC SDK I want this API to return me ```NSData```. I cannot use ```file``` data type in Swagger Specification because it maps to ```SWGFile```. ```SWGFile``` is a custom class which has ```NSData``` as an attribute. I just want ```NSData```.

I will be grateful for any help you can provide.

**Comment by wing328** [comment]
Please use `file`, which is mapped to NSURL: [ObjcClientCodegen.java#L76](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java#L76)

SWGFile should have been removed in develop_2.0 branch.

**Comment by sohail-aspose** [comment]
Sir it works. Keep up the great work!

**Comment by sohail-aspose** [comment]
I would like to know is there any library --- like ```swagger-codegen```  for client SDKs --- to auto-generate Unit tests for APIs in Objective C and other programming languages.

**Comment by sohail-aspose** [comment]
Please reply
> I would like to know is there any library --- like swagger-codegen for client SDKs --- to auto-generate Unit tests for APIs in Objective C and other programming languages.

**Comment by wing328** [comment]
The unit test you found in the sample directory are hard-coded. Currently, the project does not come with a way to automatically generate test case for a particular language.

**Comment by fehguy** [comment]
thanks @wing328.  I'm closing this
