### ISSUE TITLE
[DOTNET C#] Unable to use swagger-codegen-cli-v3 to generate typescript models with version 3.0.47

### ISSUE THREAD

**Issue by zovippro1996** [swagger-api/swagger-codegen#12240]
##### Description

We cannot able to use swagger-codegen-cli to generate typescript models anymore, this only happens after we update to the latest version 3.0.47 of [swagger-codegen-cli-v3](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli-v3)

##### Swagger-codegen version

swagger-codegen-cli-v3:3.0.47

##### Command line used for generation

(using directly from the docker image, without installing JDK/JRE locally).

docker run --rm -v $(ProjectDir)../../../:/local swaggerapi/swagger-codegen-cli-v3 generate -i ../openapi.json -l typescript-angular -Dmodels -o /local/angular/src/app/core/odata/ --additional-properties ngVersion=15

##### OpenApi JSON file
[openapi.json](https://gist.github.com/zovippro1996/feed8f250a87b0d1820eac7edb77f679)

##### Steps to reproduce

- First, using swashbuckle.aspnetcore.cli (v6.5.0) to generate openapi.json based on Swagger.
- Then, use swagger-code-gen-cli (v3.0.47) to generate typescript models

Then we receive errors as shown below:

> Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:134)
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:115)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:178)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
        at io.swagger.codegen.v3.cli.SwaggerCodegen.<clinit>(SwaggerCodegen.java:40)

##### Suggest a fix/enhancement
Right now our work-around is to stick with older version v3.0.46 until there is a fix, or we know the root cause of the problem

**Comment by rhertogh** [comment]
Not yet sure, but I suspect the change in https://github.com/swagger-api/swagger-codegen/pull/12194 to be the cause.

**Comment by zovippro1996** [comment]
@rhertogh Upgrading the version should not necessarily be the root cause, as the older version of slf4j (v1.7.36) is already old, and I always support upgrading to a newer stable version (which is v2.0.9).

Maybe the library forgets to upgrade deprecated code somewhere, or there are some dependencies that need to be updated along with updating slf4j.

**Comment by rhertogh** [comment]
@zovippro1996 To elaborate more on my answer, I think the Java Runtime in the docker container is outdated causing problems with a newer version of the Java classes. So when they are updated, they can cause the error.

**Comment by frantuma** [comment]
fixed by #12265

**Comment by rosenbjerg** [comment]
@frantuma Current latest version of v3, 3.0.51, still fails with that error. Please update the official v3 image on docker hub
