### ISSUE TITLE
Docker swagger-codegen-cli-v3:latest image broken (UnsupportedClassVersionError)

### ISSUE THREAD

**Issue by melroyvandenberg** [swagger-api/swagger-codegen#12242]
##### Description

The `swagger-codegen-cli-v3` (latest) Docker image is broken.

```bash
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

##### Swagger-codegen version

Using `swagger-codegen-cli-v3:latest` 

##### Steps to reproduce

1. Retrieve the latest version of `swagger-codegen-cli-v3:latest` from dockerhub.
2. Try running the cli command to generate the docs, meaning `generate -i definitions/api.v1.yaml -l html2 -o /local/docs` within the docker image, gives me:

```bash
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:[34](987440/jobs/5160811#step:4:35)9)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:[35](987440/jobs/5160811#step:4:36)7)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:[37](987440/jobs/5160811#step:4:38)0)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:134)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:115)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:178)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:[39](987440/jobs/5160811#step:4:40)0)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.<clinit>(SwaggerCodegen.java:[40](987440/jobs/5160811#step:4:41))
```

## Related issue

https://github.com/swagger-api/swagger-codegen/issues/12240

**Comment by frantuma** [comment]
fixed by https://github.com/swagger-api/swagger-codegen/pull/12265

**Comment by melroyvandenberg** [comment]
I still have this issue with the latest release/Docker tag (3.0.51):

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Or has there not been a release created after this fix?

**Comment by pinheiro-lucas** [comment]
> I still have this issue with the latest release/Docker tag (3.0.51):
> 
> ```
> Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> ```
> 
> Or has there not been a release created after this fix?

Same here. Probably, the docker image needs to be updated, as mentioned here https://github.com/swagger-api/swagger-codegen/issues/12240#issuecomment-1840225292

**Comment by tszxxx** [comment]
same here for version 3.0.62

**Comment by Lenormju** [comment]
@tszxxx I don't reproduce the issue, using the Docker image `swaggerapi/swagger-codegen-cli-v3:3.0.62` (which is currently the `latest` since 9 days ago). It works fine for me.
Is your local `latest` an old version ? It was the case for me, so I had to `docker image rm swaggerapi/swagger-codegen-cli-v3:latest` and re-run it (which pulled the newest `latest`, being the `3.0.62`).
