### ISSUE TITLE
Remove dependency to joda-time when using java8 dateLibrary and library jersey2

### ISSUE THREAD

**Issue by wienczny** [swagger-api/swagger-codegen#2874]
I'm currently using this pom snippet to generate client code:

```
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.1.6</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/schema.json</inputSpec>
                            <language>java</language>
                            <library>jersey2</library>
                            <configOptions>
                                <sourceFolder>swagger</sourceFolder>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                            <output>target/generated-sources</output>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

As you can see I'm using jersey2 and java8 as dateLibrary.
looking at [pom.mustache](https://github.com/swagger-api/swagger-codegen/blob/1ca246c/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache), [JSON.mustache](https://github.com/swagger-api/swagger-codegen/blob/1ca246c/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/JSON.mustache) and
 [build.gradle.mustache](https://github.com/swagger-api/swagger-codegen/blob/1ca246c/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache) you will see that joda will be required although java8 dates should be used.

When java8 is selected as dateLibrary the code should not have any dependency to joda. 

This is related to #2377.

**Comment by ralfstuckert** [comment]
Same issue if you use the feign library using java8. Problem is here the ApiClient, which still uses JodaModule:
```
import com.fasterxml.jackson.datatype.joda.JodaModule;
...
  private ObjectMapper createObjectMapper() {
    ....
    objectMapper.registerModule(new JodaModule());
    return objectMapper;
  }
```
Tried this with 2.2.0-SNAPSHOT from 06/17/2016

**Comment by wing328** [comment]
@wienczny @ralfstuckert thanks for reporting the issue.

Just yesterday, we merged https://github.com/swagger-api/swagger-codegen/pull/3174/files, which is related to java8, dateLibrary and jersey2.

I wonder if you can pull the latest to give it a try.

**Comment by wing328** [comment]
cc @cbornet

**Comment by ralfstuckert** [comment]
Hmm, still getting this problem. But since I'm working with a snapshot, I wonder if some caching tricks me here. So I can't tell 100%, sorry.

**Comment by wing328** [comment]
@ralfstuckert np. thanks for giving it a try. To fix it we need to do the following for `java8` dateLibrary oiption:
- remove `import com.fasterxml.jackson.datatype.joda.JodaModule;`
- remove `    objectMapper.registerModule(new JodaModule());`

If that's correct, I can submit a PR for Java Feign API client.

**Comment by cbornet** [comment]
I think this is fixed on master by #3065

**Comment by cbornet** [comment]
This has been done for jersey1/jersey2 and can be done for all java clients.
This is simple jackson config for Feign. For gson based libs, TypeAdapter classes might be needed. I can work on that if needed.

**Comment by wing328** [comment]
@cbornet thanks. Please file a PR when you've time.

**Comment by wing328** [comment]
@wienczny @ralfstuckert please pull the latest master to give it a try.

Thanks for the PRs from @cbornet

**Comment by ralfstuckert** [comment]
:+1: 
```  
private ObjectMapper createObjectMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    ...
    objectMapper.registerModule(new JavaTimeModule());
    return objectMapper;
  }
```

**Comment by IngvarJackal** [comment]
though no import, ```objectMapper.registerModule(new JavaTimeModule());``` still exists
