### ISSUE TITLE
[Ruby] Ssl avoidance problem

### ISSUE THREAD

**Issue by donFotter** [swagger-api/swagger-codegen#3269]
Hi, 
I've generated various clients of my Api. I'm in the development phase, so I've to turn off ssl verification. Every client works fine, except the ruby's one. In particular, even if I set the "verify_ssl" to false in the "configuration.rb" file, it continues to work with ssl, with no success. I've activated the debug mode and it shows that it still try to use ssl, finishing with unsuccess. I've checked if there was some firewall problem or admin rights problem, but it's all ok. Even if I declare globally to ignore ssl (OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE)
What can I do? Is this a bug of the codegen?

I'm using Swagger-codegen version 2.1.6

**Comment by wing328** [comment]
@donFotter please pull the latest master to generate the Ruby API client, which has all the dependencies updated to the latest version (the issue you reported may be due to a bug in the HTTP library, which can already be addressed in the latest stable version of that library)

**Comment by donFotter** [comment]
Hi, thank you for fast response. I've try just now with the master, but the problem still persist. 
Any suggestion?

**Comment by wing328** [comment]
@donFotter Btw, you do not need to manually change configuration.rb. You should probably do it in the code level when creating a configuration object, which can be pass to Api class (e.g. PetApi) via constructor.

No other suggestion off the top of my head.

**Comment by donFotter** [comment]
Yes I know, I did it for the basic auth inf., I just changed the value in the configuration.rb hoping that this solved, but nope :(.

**Comment by wing328** [comment]
What about hardcoding "false" in the following line in the api_client.rb?

https://github.com/swagger-api/swagger-codegen/blob/07a852fe78ae71261f617200459e2cdf6529068f/samples/client/petstore-security-test/ruby/lib/petstore/api_client.rb#L108

**Comment by donFotter** [comment]
I've tried this too, didn't work

**Comment by wing328** [comment]
Can you check which version of Typhoeus you're using?

**Comment by donFotter** [comment]
Typhoeus 1.0.2

**Comment by wing328** [comment]
No idea. Please open an issue [here](https://github.com/typhoeus/typhoeus/issues) with the debug log to see if the typhoeus team or community has encountered similar issue before.

**Comment by donFotter** [comment]
The friends of Typhoeus have found the fix: there is another value to be set for ignore ssl, that is ssl_verifyhost (https://github.com/typhoeus/typhoeus#ssl). This isn't present in the generated code. Adding this option, the problem was solved. I'm attaching a screenshot to clarify the solution
![ssl](https://cloud.githubusercontent.com/assets/20241211/16561136/e3328980-41f7-11e6-9479-22e665bfca11.png)

Thank you very much for the support. Have a nice day!

**Comment by wing328** [comment]
@donFotter Thanks for the info. We'll add another option `verify_ssl_host` to make "ssl_verifyhost" configurable.

**Comment by wing328** [comment]
@donFotter I've merged #3283 to add the `verify_ssl_host` option (which is set to true by default).

Please pull the latest master to give it a try.

**Comment by donFotter** [comment]
Sorry for the delay, now it's fine

**Comment by wing328** [comment]
@donFotter np. Please let us know if you've further feedback on the client.
