### ISSUE TITLE
[java] swagger-core, codegen issue related to '$ref' references to files - no files are generated

### ISSUE THREAD

**Issue by derandreasberger** [swagger-api/swagger-codegen#3614]
##### Description
Hello!

We've been trying to setup an API spec with multiple domain-objects (model-objects) and several paths. It seems like we're hitting either a nesting-issue with references or an empty definitions problem I think.

Impact:
1. If we use absolute refs, we can generate no code:
`[main] INFO io.swagger.parser.Swagger20Parser - reading from bugDemoSpec.yaml
Exception in thread "main" java.lang.RuntimeException: Could not find definitions/AnotherObjectSameLevel in contents of ./levelOneAbs/levelTwoAbs/levelThreeAbs/subFolder/AnotherObject.yaml
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:118)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:30)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:71)
        at io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:92)
        at io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:33)
        at io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:44)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:26)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:89)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:390)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)`

2. If we use relative refs we won't get no code (not even a folder) for our model definitions.

##### Swagger-codegen version
2.2.1
##### Swagger-core version
1.5.9

##### Swagger declaration file content or url
https://github.com/derandreasberger/temporaryDemoRepository

##### Command line used for generation
java -jar -DdebugModels=true swagger-codegen-cli-2.2.1.jar generate -i bugDemoSpec.yaml -l spring -o target/server/demo/

##### Steps to reproduce
Download demo-project from git, copy swagger-codegen-cli-2.2.1.jar to the downloaded directory and run above java/swagger-codegen command

##### Related issues
?

##### Suggest a Fix
Improve support of multiple files / refs, i.e. fix the bug causing the exception.

**Comment by jeff9finger** [comment]
I am having similar issues. The issue is in swagger-parser. It gets confused as to what the base directory is when inspecting a file that is lower than the base level.

For example:
base/swagger.yaml
  subdir1/subfile1.yaml
  subdir2/subfile2.yaml


If subfile1.yaml contains a reference:
   $ref: '../subdir2/subfile2.yaml#/definitions/AModel

The swagger-parser gets confused.

**Comment by KaelenProctor** [comment]
I am also encountering this error and it seems to occur when a file in a sub-folder references files in any other subfolder. I've created several test cases for various ways of splitting a simple swagger file up, and the cases that fail most (ie an exception) are when a subfile refers to file above it in another subfolder or when the subfile refers to a file further down in the directory structure. Those are seen in cases 8-10 in the attached zip of test cases.

[swagger-relative-file-references.zip](https://github.com/swagger-api/swagger-codegen/files/548613/swagger-relative-file-references.zip)

**Comment by fehguy** [comment]
Please open this issue on swagger-parser.  That's where the logic lives, and we can address it there.

**Comment by fehguy** [comment]
This should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4094/commits/92af2cf8211a61291547eee137fdddaf862495e1

**Comment by maheshmahadevan** [comment]
Has this been fixed , i am still facing the problem with v2.3.0
