### ISSUE TITLE
Warning printed when generating static html docs

### ISSUE THREAD

**Issue by davidsantiago** [swagger-api/swagger-codegen#3874]
##### Description

When using language 'html', the generator spits out repeated warnings: 

```
escapeUnsafeCharacters should be overridden in the code generator with proper logic to escape unsafe characters
escapeUnsafeCharacters should be overridden in the code generator with proper logic to escape unsafe characters
escapeUnsafeCharacters should be overridden in the code generator with proper logic to escape unsafe characters
```
(Many more times than I've quoted here). 

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Command line used for generation

Called from gradle tasks with the following options:

      inputSpec = './src/main/resources/spec.yaml'

      output = 'build/api_docs'
      language = 'html'

      additionalProperties = sharedAdditionalProperties
      
##### Steps to reproduce

Run the generator on language 'html'. 

##### Suggest a Fix

It appears to be related to this line of code: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L362

The Static HTML generator does not override this method: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java

Naively, it looks to me like this function should be implemented, even if only to suppress the warning, which a user can't do anything about. But I definitely don't understand the code injection issue the code is intending to prevent. I looked at the Java and Swift implementations of this method and do not understand it, for example. Otherwise, happy to help push this forward.

**Comment by wing328** [comment]
@davidsantiago thanks for reporting the issue. I should be able to come up with a fix by tomorrow.

**Comment by wing328** [comment]
@davidsantiago fixed via #3897. Please pull the latest master to give it a try.

**Comment by DavidBiesack** [comment]
Until 2.2.2 makes it into Maven Central, is there a workaround - a command line option, or a system property, that we can use to suppress these warnings?

**Comment by davidsantiago** [comment]
I never found one. I use a custom build from head. I am surprised that after months of development, a 0.0.1 version bump release has still not been cut.

**Comment by evanbross** [comment]
I just hit this problem with 2.2.1, any ETA for 2.2.2?

**Comment by wing328** [comment]
@evanbross I think it's reasonable to target Jan/Feb 2017 for 2.2.2 release.

For the time being, please pull the JAR locally and run `mvn clean install` to install the package to the local Maven store.

**Comment by staticcat** [comment]
Just hit this issue with converting a swagger json file into a yaml file. Would this mean the YAML static code generator would also need to be patched as well as the HTML generator?

**Comment by wing328** [comment]
@staticcat yes, please open a new issue for tracking and we'll look into that.

**Comment by wing328** [comment]
@staticcat I've fixed the warnings via #4827 . Please pull the latest master to give it a try.

**Comment by staticcat** [comment]
@wing328 tested with #4827 and found to no longer be writing out the warnings.
