### ISSUE TITLE
[Python] deserialization of readOnly properties fail on swagger_client

### ISSUE THREAD

**Issue by yucer** [swagger-api/swagger-codegen#4174]
##### Description

When a property is marked as readonly, the property deserialization fails in Python generated code.

##### Swagger-codegen version

The generator used by the online Swagger Editor. http://editor.swagger.io/

I don't know the version, but I will explain below why it doesn't matter given that the failing section of the generated code is the same that stays in the last version of python templates.  

##### Swagger declaration file content or url

Go there and select the YML example: **Swagger Petstore (Simple)** adding a readonly property to the *pet* definition, like this:

```yaml 
definitions:
  pet:
    type: object
    required:
      - id
      - name
      - father
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      father:
        type: string
        readOnly: true
      tag:
        type: string
```

The test server side can generated in the same online generator (Generate Server -> Python Flask), changing the code  of the default controller to:

```python
pet_index = {}

def add_pet(pet) -> str:
    pet['father'] = 'Pirulay'
    pet_index[pet['id']] = pet
    return pet

def delete_pet(id) -> str:
    del pet_index[id]

def find_pet_by_id(id) -> str:
    return pet_index[id]

def find_pets(tags = None, limit = None) -> str:
    return [p for p in pet_index.values()[:limit or len(pet_index)]]
```

The client side can be generated also there: "Generate Client -> Python"

##### Steps to reproduce

This code sequence:

```python
import swagger_client
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
# create an instance of the API class
swagger_client.configuration.host = 'http://127.0.0.1:8080/api'
api_instance = swagger_client.DefaultApi()
pet = swagger_client.NewPet() # NewPet | Pet to add to the store

pet.name = 'Pirulay'
pet.id = 1
pet.tag = 'dog'

try:
    api_response = api_instance.add_pet(pet)
    pprint(api_response)
except ApiException as e:
    print "Exception when calling DefaultApi->add_pet: %s\n" % e
```

It raises the following exception:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c38bea27c82e> in <module>()
      1 try:
----> 2     api_response = api_instance.add_pet(pet)
      3     pprint(api_response)
      4 except ApiException as e:
      5     print "Exception when calling DefaultApi->add_pet: %s\n" % e

/home/yucer/src/experiments/swagger/python-client/swagger_client/apis/default_api.pyc in add_pet(self, pet, **kwargs)
     76             return self.add_pet_with_http_info(pet, **kwargs)
     77         else:
---> 78             (data) = self.add_pet_with_http_info(pet, **kwargs)
     79             return data
     80 

/home/yucer/src/experiments/swagger/python-client/swagger_client/apis/default_api.pyc in add_pet_with_http_info(self, pet, **kwargs)
    154                                             auth_settings=auth_settings,
    155                                             callback=params.get('callback'),
--> 156                                             _return_http_data_only=params.get('_return_http_data_only'))
    157 
    158     def delete_pet(self, id, **kwargs):

/home/yucer/src/experiments/swagger/python-client/swagger_client/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    332                                    path_params, query_params, header_params,
    333                                    body, post_params, files,
--> 334                                    response_type, auth_settings, callback, _return_http_data_only)
    335         else:
    336             thread = threading.Thread(target=self.__call_api,

/home/yucer/src/experiments/swagger/python-client/swagger_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    161         # deserialize response data
    162         if response_type:
--> 163             deserialized_data = self.deserialize(response_data, response_type)
    164         else:
    165             deserialized_data = None

/home/yucer/src/experiments/swagger/python-client/swagger_client/api_client.py in deserialize(self, response, response_type)
    251             data = response.data
    252 
--> 253         return self.__deserialize(data, response_type)
    254 
    255     def __deserialize(self, data, klass):

/home/yucer/src/experiments/swagger/python-client/swagger_client/api_client.py in __deserialize(self, data, klass)
    294             return self.__deserialize_datatime(data)
    295         else:
--> 296             return self.__deserialize_model(data, klass)
    297 
    298     def call_api(self, resource_path, method,

/home/yucer/src/experiments/swagger/python-client/swagger_client/api_client.py in __deserialize_model(self, data, klass)
    588                 value = data[instance.attribute_map[attr]]
--> 589                 setattr(instance, attr, self.__deserialize(value, attr_type))
    590 
    591         return instance

AttributeError: can't set attribute
``` 

The attr field in that moment has the value: *father*. Corresponding to the new readonly field. 

##### Suggest a Fix

The setter decorator is not generated for the readonly fields, so the field can not be updated. But it should receive at least the first time the value.

There is a little difference in assignment when we talk about *deserialization*. It is not a normal assignment.

While the readonly property protect us from an object state change, like this:

```python
self.father = 'Pirulay'
```

During serialization one should ensure the exact state that the object had when it was serialized. So we should assign the father anyway. I propose:

```python
self._father = 'Pirulay'
```

And I have tested that changing that line to this code works:

```python
589                 setattr(instance, '_' + attr, self.__deserialize(value, attr_type))
```

Also I would advice to split that line in two:

```python
589                 d_value = self.__deserialize(value, attr_type)
590                 setattr(instance, '_' + attr, _value)
``` 

That way we know just looking the stack trace if the problem was during the deserialization or the assignment.

**Comment by wing328** [comment]
@yucer the issue should have been addressed via https://github.com/swagger-api/swagger-codegen/pull/3591

Please pull the latest master, build the JAR locally and generate Python API client to give it a try.

**Comment by yucer** [comment]
I think that the solution that I have proposed is better, because the python object can still have the readOnly check after the serialization, as specified by the spec.  

But, anyway... Now there is not error. So the error will be for those dare to assign values to that field. ;-)

Thank you very much, and sorry for the late feedback.

**Comment by wing328** [comment]
Np. Let us know if you need further assistance.
