### ISSUE TITLE
mvn:package does not work on Java 8

### ISSUE THREAD

**Issue by Ueland** [swagger-api/swagger-codegen#475]
"mvn package" ends up in the following error:

[WARNING]  Expected all dependencies to require Scala version: 2.10.0
[WARNING]  org.scalatest:scalatest_2.10:2.1.4 requires scala version: 2.10.3
[WARNING] Multiple versions of scala libraries detected!
[INFO] /home/..../swagger-codegen/modules/swagger-generator/src/test/scala:-1: info: compiling
[INFO] Compiling 1 source files to /home/..../swagger-codegen/modules/swagger-generator/target/test-classes at 1425911873929
Downloading: http://.....:9090/nexus/content/groups/public/org/scala-lang/scala-reflect/2.10.0/scala-reflect-2.10.0.jar
Downloaded: http://.....:9090/nexus/content/groups/public/org/scala-lang/scala-reflect/2.10.0/scala-reflect-2.10.0.jar (3076 KB at 9763.6 KB/sec)
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
[ERROR] two errors found

A quick google search appears to conclude with missing java8 support.

**Comment by webron** [comment]
Just ran it with no issue. Which branch do you use?

**Comment by Ueland** [comment]
master, should i switch to another one?

Only did a git clone, and went straight for the mvn command.

**Comment by webron** [comment]
Right, I just ran it as `mvn clean package` and I see the issue now.

**Comment by webron** [comment]
For me, only swagger-generator is failing, and that's shouldn't stop you from using the codegen for now unless you're looking for a hosted solution (like http://generatior.swagger.io).

Still need to be resolved, of course.

**Comment by bklang** [comment]
> that's shouldn't stop you from using the codegen for now unless you're looking for a hosted solution (like http://generatior.swagger.io).

I'm following the instructions on the README to generate a static HTML version of my API documentation. The instructions reference `swagger-codegen/modules/swagger-codegen-distribution/target/swagger-codegen-distribution-2.1.0-M1.jar`, which doesn't seem to exist because of this issue.  From your comment, is there a way to generate static HTML docs without compiling codegen?

**Comment by bklang** [comment]
Please disregard my last comment: I was getting generator confused with codegen. I was able to get it to run.  Minor note: the README should be updated to refer to version `2.1.2`, but that's trivial.

**Comment by fehguy** [comment]
Thank you--I've updated both master and the develop_2.0

**Comment by fehguy** [comment]
the jdk8 issue was a scala bug, fixed by updating to 2.10.4.  Pushed to develop_2.0

**Comment by Ueland** [comment]
Thanks! :)

**Comment by Ueland** [comment]
mvn package does still fail with the same error message as before here.

git status
# On branch develop_2.0

**Comment by webron** [comment]
Just tested it locally with java 8 and develop_2.0 and it compiles fine.

Can you try running `mvn clean package`?

**Comment by Ueland** [comment]
Last bit of output from "mvn clean package" pasted here:
http://pastebin.com/pKfWLGEX 

Verification of branch open:
git branch
* develop_2.0
  master

**Comment by webron** [comment]
Are you sure you pulled in the changes for the develop_2.0 branch?
In your log, this line shows:
``[WARNING]  Expected all dependencies to require Scala version: 2.10.0``

In mine it shows:
``[WARNING]  Expected all dependencies to require Scala version: 2.10.4``

**Comment by Ueland** [comment]
As suspected, user error on my part. Working just fine now, thanks!

**Comment by webron** [comment]
No worries, thanks for keeping us posted.
