### ISSUE TITLE
[TypeScript-*] Generating array of enum values fails to create TS enums

### ISSUE THREAD

**Issue by kirpit** [swagger-api/swagger-codegen#5681]
##### Description

Basically trying to combine `type: array` and `enum: [ ... ]` within a single field, so we can limit the possible parameters to be passed, as seen in the official docs [here](http://swagger.io/docs/specification/describing-parameters/).

There are two ways to do this; one is specifying directly in-place, another is to give reference to a definition, and the both cases fail similarly to create the enum values on TypeScript models. In other words, enum definitions within the swagger spec fades away and has no effect.

##### Swagger-codegen version

Latest master; 802641b.

##### Swagger declaration file content or url

```yaml
swagger: "2.0"
info:
  version: "1.0"
  title: "Hello World API"
paths:
  /hello:
    get:
      parameters:
        - name: myData
          in: body
          schema:
            properties:
              myNumbersField:
                # In-place field spec:
                type: array
                items:
                  type: number
                  enum:
                    - 1
                    - 2
              myStringsField:
                # Reference to the definition: 
                $ref: '#/definitions/ArrayOfStringChoicesModel'
      responses:
        200:
          description: Returns the greeting.

definitions:
  ArrayOfStringChoicesModel:
    type: array
    items:
      type: string
      enum:
        - foo
        - bar
```

Example output (typescript/fetch):
```
export interface ArrayOfStringChoicesModel extends Array<string> {
}

export interface MyData {
    "myNumbersField"?: Array<number>;
    "myStringsField"?: ArrayOfStringChoicesModel;
}
```

That has no enum values defined at all.

##### Command line used for generation

Regular `java -jar swagger-codegen-cli.jar generate -i spec.yml -l {language}` call with any of the typescript/framework pair as far as I'm aware of:

* typescript-angular2 
* typescript-angular 
* typescript-jquery 
* typescript-node 
* typescript-fetch

##### Steps to reproduce

Most convenient way to reproduce (perhaps with the latest stable) is swagger editor: 

1. Go to http://editor.swagger.io/
2. Paste the above spec yaml
3. Generate client / download any of the TypeScript choice.
4. Alternatively, run the generate command with the given yaml spec

##### Related issues

* This also reproduces the bug #3616 for typescript/angular2, which will be ignored here.
* Not to be confused with already resolved issue #4577.
* Might have weak relation to #2739.

##### Suggest a Fix

Can help if the issue is addressed correctly.

**Comment by macjohnny** [comment]
@kirpit recently, some changes regarding enums have been comitted. could you retry with the current master and close the issue if it is resolved?

**Comment by kirpit** [comment]
Will do that a.s.a.p (that probably means sometime in the weekend). Thanks for the heads up!

**Comment by kenisteward** [comment]
@kirpit I'm fixing this as a part of a PR right now for typescript-node.  typescript-angular is already fixed i'd have to look into others as they all have different model generators :x.

**Comment by kirpit** [comment]
Unfortunately the problem is still consist with minor improvement on `typescript-angular` (previously known as `typescript-angular2`) definition:

```
export interface MyData {
    myNumbersField?: Array<number>;  // <------ Definition looks like fixed
    myStringsField?: ArrayOfStringChoicesModel;
}
```
However, enum set of values are not there at all, so they have no effect. 

Tried with `typescript-angular`, `typescript-angularjs` and `typescript-fetch` but not others, against current master 4dafa5b92.

**Comment by kenisteward** [comment]
The arrayofstringchoices model I don't believe was a properly setup enum.
Currently it only supports the enum being on the response and not in the
definition so we may need to do more.

**Comment by kenisteward** [comment]
@kirpit what you linked me is showing 2.2.3 not 2.3.0 snapahot try doing mvn clean package on current master. I know the arrayofstringchoices model is probably not fully correct but the other should be. Also my ts-node pr has not been merged yet

**Comment by kirpit** [comment]
It is `2.3.0`, the latest commit content must have confused you.

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar version
2.3.0-SNAPSHOT
```
And I already compiled with `mvn clean package` from the newly cloned _latest master_.
