### ISSUE TITLE
Headers do not appear in static html documentation

### ISSUE THREAD

**Issue by arketec** [swagger-api/swagger-codegen#5930]
##### Description
StaticHtmlGenerator does not include custom header definitions. I have an endpoint that may pass a token in a custom header 'x-access-token' or as a query parameter 'token'

In the swagger.yaml file:

```yaml(
parameters: 
        - name: x-access-token
          in: header
          type: string
          required: false
        - name: token
          in: query
          type: string
          required: false

```

This works in the swagger editor, as well as through an HTTP client (like SOAP UI)

However, when I generate the static HTML docs, the header section is blank.

##### Swagger-codegen version

swagger-codegen-cli 2.2.2
##### Command line used for generation
java -jar ./swagger-codegen-cli.jar generate -l html -i ./api/swagger/swagger.yaml

##### Steps to reproduce
Run the above command

**Comment by wing328** [comment]
@noahm888 please try the latest master as the issue might have been addressed.

**Comment by noahm888** [comment]
@wing328  I have the latest master, but the problem persists when using 'html' as the lanq option. However, looking through the source, I found a second html generator called 'html2'. It uses a different template, but it does include the custom headers in the generation. So, I will use this as a work-around.

**Comment by wing328** [comment]
@noahm888 thanks for using the latest master to confirm it's still an issue.

We'll mark this as an issue and see if anyone from the community has time to contribute a fix.

**Comment by noahm888** [comment]
Awesome, thanks!

**Comment by noahm888** [comment]
Accidentally closed :)

**Comment by hunterv** [comment]
In case someone else has this issue before it gets fixed:
[Go to this file](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache)  
Line 86 is: {{#headerParam}}{{>headerParam}}{{/headerParam}}
Change it to: {{#headerParam**s**}}{{>headerParam}}{{/headerParam**s**}} (add S's)

**Comment by frantuma** [comment]
fixed in #8669
