### ISSUE TITLE
[Java] [JAX-RS] parameters model-package / api-package have no effect

### ISSUE THREAD

**Issue by pneumcke** [swagger-api/swagger-codegen#8708]
##### Description

The parameters model-package and api-package have no effect, java files are being created with package "io.swagger".

##### Swagger-codegen version

3.0.0

##### Swagger declaration file content or url

sample petstore.yaml from https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Command line used for generation

java -jar swagger-codegen-cli-3.0.0.jar generate -i petstore.yaml -l jaxrs-spec --api-package=test.api --model-package=test.model

##### Steps to reproduce

Execute command line above. Result is:

`src`
`-- gen`
`    -- java`
`        |-- io`
`        |   -- swagger`
`        |       |-- api`
`        |       |   -- PetsApi.java`
`        |       -- model`
`        |           |-- Error.java`
`        |           |-- Pet.java`
`        |           -- Pets.java`
`        -- test`
`            -- RestApplication.java`

api and model should be in the defined "test" package, just as the RestApplication class.

**Comment by thejjmiller** [comment]
I have the same problem. Any workarounds?

**Comment by knap1930** [comment]
+1 same issue

**Comment by HugoMario** [comment]
thanks for filing this, gonna try to get it fix asap

**Comment by knap1930** [comment]
duplicate issue here: https://github.com/swagger-api/swagger-codegen-generators/issues/76

**Comment by frantuma** [comment]
Fixed in swagger-api/swagger-codegen-generators#560

**Comment by smargoli2** [comment]
This is still an issue for the C# generated code. model-package does not work properly.
