### ISSUE TITLE
[spring] @RequestPart should use "{{basename}}" instead of "file" and observe "required" attribute

### ISSUE THREAD

**Issue by 6d77** [swagger-api/swagger-codegen#9250]
##### Description

When generating a spring-boot server for a POST processing multipart form data to upload one or several files, then the generated @RequestPart annotation always uses the fixed string "file" instead of the name of the part. Additionally, the required attribute is not considerd when building the @RequestPart annotation, so that file upload parameters are always required even if not defined to be so in the Swagger yaml file.

##### Swagger-codegen version

swagger-codegen-cli-2.4.2.jar

##### Swagger declaration file content or url

If you post the code inline, please wrap it with
```yaml
  /kpack/jsonld:
    post:
      operationId: "uploadJsonld"
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: jsonld
          in: formData
          type: file
          description: "JSON-LD graph file"
          required: true
```

##### Command line used for generation

```bash
java -jar ./swagger-codegen-cli.jar generate \
	-i api.yaml \
	-l spring 
```

##### Steps to reproduce

Create code with command given above. Check generated Api and Controller.

##### Suggest a fix/enhancement

In https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/formParams.mustache change the fixed "file" and replace it by "{{basename}}". Additionally fill the "required" attribute of this annotation.

**Comment by MGoyal92** [comment]
Changing formParams.mustache to the below seems to fix the issue:

`{{#isFormParam}}{{#notFile}}@ApiParam(value = "{{{description}}}"{{#required}}, required=true{{/required}}{{#allowableValues}}, allowableValues="{{#values}}{{{.}}}{{^-last}}, {{/-last}}{{#-last}}{{/-last}}{{/values}}"{{/allowableValues}}{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}) @RequestParam(value="{{baseName}}"{{#required}}, required=true{{/required}}{{^required}}, required=false{{/required}})  {{{dataType}}} {{paramName}}{{/notFile}}{{#isFile}}@ApiParam(value = "{{{description}}}") {{#useBeanValidation}}@Valid{{/useBeanValidation}} @RequestPart(value="{{baseName}}"{{#required}}, required=true{{/required}}{{^required}}, required=false{{/required}}) MultipartFile {{baseName}}{{/isFile}}{{/isFormParam}}`

**Comment by frantuma** [comment]
thanks for reporting this! fixed in #9490

**Comment by mhaarika** [comment]
Which springfox version is this fixed. i am using springfox 2.9.2 version and this still exists

**Comment by MGoyal92** [comment]
> Which version of code gen is this fixed

I'm not sure about the version, but it was merged 1.5 years back. You can find the details under #9490 
"frantuma merged commit b028473 into swagger-api:master on Nov 21, 2019"

**Comment by mladenlukic** [comment]
This is still happening with version 3.0.35
