### ISSUE TITLE
[JAVA] Bug generating `SnakeException: Exception safe-checking yaml content` but only with yaml input file.

### ISSUE THREAD

**Issue by hectoralicea** [swagger-api/swagger-codegen#9268]
##### Description
Getting `SnakeException: Exception safe-checking yaml content` when I run `swagger-codegen generate` on a particular yaml input file. It works with the equivalent converted json input file.  It also generates the same code between the two formats.

```
[main] ERROR io.swagger.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:109)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:69)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalAccessError: tried to access field org.yaml.snakeyaml.constructor.BaseConstructor.composer from class io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
	... 10 more
```

##### Swagger-codegen version

swagger-codegen version
2.4.2

##### Swagger declaration file content or url

(swagger file is proprietary.  Please DM me for a gist URL.)

##### Command line used for generation

Following is what I use to create the java generated code.
```
swagger-codegen generate \
  -i major-sub-agent.yaml \
  --api-package   org.rc.ecyd.major.person.api \
  --model-package org.rc.ecyd.major.person.model \
  --group-id      org.rc.ecyd.major.person \
  --artifact-id   major-sub-agent \
  --artifact-version 0.0.1-SNAPSHOT \
  -l spring \
  -o ../major-sub-agent
```
##### Steps to reproduce

get the yaml file from my gist, and run the above command.

##### Related issues/PRs

None that I know of.

##### Suggest a fix/enhancement

Handle the exception correctly.

**Comment by bangdh** [comment]
I have the same problem

**Comment by mapad** [comment]
I have the same problem with the yaml example file https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-expanded.yaml
This is failing with swagger-codegen **v2.4.2**, but it works with **v2.3.1**

**Comment by frantuma** [comment]
#9243 fixes the reported error in latest 2.4.3-SNAPSHOT (available on sonatype snapshots repo and upcoming release). Closing ticket, please reopen if this doesn't solve your issue

**Comment by hectoralicea** [comment]
will this fix #9243 also be fixed in the 3.x code branch?  I believe this issue occurred in the 3.x version as well.

**Comment by frantuma** [comment]
yes, by #9237

**Comment by kumarroshan** [comment]
I have upgraded dependencies as below from 2.4.2  to 2.4.4 .
io.swagger:swagger-codegen:2.4.4
io.swagger:swagger-codegen-cli:2.4.4

But , I am still getting above stacktrace errorlog.
