### ISSUE TITLE
[Python] Missing import when generating Flask server

### ISSUE THREAD

**Issue by Rictus** [swagger-api/swagger-codegen#9864]
##### Description

I generate my models with Swagger codegen 2.4.9.  Looking at the generated models, there is a missing import in one of the classes.This would raise a SyntaxError and prevent to use the codegen in automatic process such as ci/cd.

##### Swagger-codegen version

The bug is not present in Swagger codegen 2.4.8. This is a regression happening since Swagger codegen 2.4.9.

##### Swagger declaration file content or url
The generated code : https://gist.github.com/Rictus/5f34f54cb83962190eeb240ad82ea5db
The yaml : https://gist.github.com/Rictus/556ebbaf6763d2ee6daeaa0e1ee68abc

##### Command line used for generation

```bash

CODEGEN_JAR=swagger-codegen-cli.jar
SWAGGER_FILE=swagger_server/swagger/swagger.yaml
CODEGEN_VERSION=2.4.9

# download code generator if is not present
wget -nc http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/${CODEGEN_VERSION}/swagger-codegen-cli-${CODEGEN_VERSION}.jar -O ${CODEGEN_JAR}

# launch code generator
java -jar ${CODEGEN_JAR} generate -Dmodels -i ${SWAGGER_FILE}  -l python-flask -o ./
```

##### Steps to reproduce

* Generate models using Swagger generator 2.4.9
* Look at `training_config.py`, there is a missing import : `ColumnList`. The file do exist

##### Related issues/PRs

Similar issue https://github.com/swagger-api/swagger-codegen/issues/9829

##### Suggest a fix/enhancement

I think the model inheritance have something to do here. It does not work well with new property having a model reference.

**Comment by risik** [comment]
The bug still present in version 2.4.10

**Comment by HugoMario** [comment]
Hey @Rictus  @risik 

i think this issue was addressed on latest versions, can you please check when you have a chance?

**Comment by HugoMario** [comment]
i tested locally with given input yaml and seems ok for me. Going to close it for now. But will reopen it and work on it asap if you got the issue.

**Comment by markwimpory** [comment]
I think this is still not working.  I have a model, that has another model as an attribute, and there is no import for it.  I rebuilt from master today

**Comment by HugoMario** [comment]
@markwimpory ,

i'll check that

**Comment by rondiplomatico** [comment]
I'm also experiencing this issue with missing imports.
Using the below geojson-like yaml at any property correctly creates both model files, but forgets adding the import `from <pkg-name>.models.feature_properties import FeatureProperties` to `feature.py`

This also pertains if i'm defining the properties object directly inside feature.

```
feature:
    type: object
    required:
      - type
      - geometry
      - properties
    properties:
      type:
        type: string
        enum:
          - Feature
      properties:
        $ref: "#/definitions/featureProperties"
      geometry:
        type: string
   
  featureProperties:
    type: object
    required:
      - name
    properties:
      id: 
        type: string
        example: "DE21"
      name: 
        type: string
        example: "Bayern"
      value:
        type: number
        example: 45
```

**Comment by risik** [comment]
Sorry for too long. Early I faced the same problem for 3.0.x branch.

I just re-tested some versions in 3.x branch with my own project. I got results:
* swagger_version 3.0.14: OK
* swagger_version 3.0.15: FAIL
* swagger_version 3.0.16: FAIL
* swagger_version 3.0.17: OK
* swagger_version 3.0.18: OK
* swagger_version 3.0.19: OK
* swagger_version 3.0.20: OK
* swagger_version 3.0.21: OK

So looks like it fixed since 3.0.17.

Also I tested it with @Rictus specification example (https://gist.github.com/Rictus/556ebbaf6763d2ee6daeaa0e1ee68abc) against 2.4.x swagger-codegen-cli from 2.4.8 to the latest 2.4.15. Only 2.4.8 work OK. 

Some additional details...
For example here the difference between 2.4.8 and 2.4.9-2.4.15 generated code:
```
$ diff 2.4.8/swagger_server/models/training_config.py 2.4.15/swagger_server/models/training_config.py
9,10d8
< from swagger_server.models.columns_list import ColumnsList  # noqa: F401,E501
< from swagger_server.models.config import Config  # noqa: F401,E501
```

**Comment by nguyena7** [comment]
I'm curious, is there a reason was to why these lines were removed in v2.4.9 and above? Could this be the reason for this bug?
https://github.com/swagger-api/swagger-codegen/blob/453bbf305fae3029b89ca99934035ef3cb98b37a/modules/swagger-codegen/src/main/resources/flaskConnexion/model.mustache#L9

**Comment by HugoMario** [comment]
this is already fixed by https://github.com/swagger-api/swagger-codegen/pull/11742
